//
//  variables.swift
//  rus-project
//
//  Created by Evgenii Pakhomov on 17.09.2021.
//

import Foundation
import SwiftUI

struct Word {
    var rule = 0;
    var label = "";
    var correct = "";
    var options = [""];
}

let Words = [
    Word(rule: 1, label: "бл_стать", correct: "блистать", options: ["блистать", "блестать"]),
    Word(rule: 1, label: "бл_стящий", correct: "блестящий", options: ["блестящий", "блистящий"]),
    Word(rule: 1, label: "выж_гший", correct: "выжегший", options: ["выжегший", "выжигший"]),
    Word(rule: 1, label: "выж_чь", correct: "выжечь", options: ["выжечь", "выжичь"]),
    Word(rule: 7, label: "вым_кнуть", correct: "вымокнуть", options: ["вымокнуть", "вымакнуть"]),
    Word(rule: 8, label: "выпл_влять", correct: "выплавлять", options: ["выплавлять", "выпловлять"]),
    Word(rule: 9, label: "выр_внять", correct: "выровнять", options: ["выровнять", "выравнять"]),
    Word(rule: 12, label: "выр_щивать", correct: "выращивать", options: ["выращивать", "вырощивать"]),
    Word(rule: 10, label: "выск_чка", correct: "выскочка", options: ["выскочка", "выскачка"]),
    Word(rule: 1, label: "выч_сть", correct: "вычесть", options: ["вычесть", "вычисть"]),
    Word(rule: 1, label: "выч_т", correct: "вычет", options: ["вычет", "вычит"]),
    Word(rule: 1, label: "выч_тать", correct: "вычитать", options: ["вычитать", "вычетать"]),
    Word(rule: 1, label: "выч_ты", correct: "вычеты", options: ["вычеты", "вычиты"]),
    Word(rule: 2, label: "г_релка", correct: "горелка", options: ["горелка", "гарелка"]),
    Word(rule: 2, label: "г_релый", correct: "горелый", options: ["горелый", "гарелый"]),
    Word(rule: 3, label: "з_рница", correct: "зарница", options: ["зарница", "зорница"]),
    Word(rule: 3, label: "з_ря", correct: "заря", options: ["заря", "зоря"]),
    Word(rule: 1, label: "забл_стел", correct: "заблестел", options: ["заблестел", "заблистел"]),
    Word(rule: 2, label: "заг_релый", correct: "загорелый", options: ["загорелый", "загарелый"]),
    Word(rule: 2, label: "заг_реть", correct: "загореть", options: ["загореть", "загареть"]),
    Word(rule: 1, label: "зад_рать", correct: "задирать", options: ["задирать", "задерать"]),
    Word(rule: 5, label: "закл_натель", correct: "заклинатель", options: ["заклинатель", "закленатель"]),
    Word(rule: 1, label: "зам_рать", correct: "замирать", options: ["замирать", "замерать"]),
    Word(rule: 1, label: "зан_мать", correct: "занимать", options: ["занимать", "занемать"]),
    Word(rule: 1, label: "зап_рать", correct: "запирать", options: ["запирать", "заперать"]),
    Word(rule: 9, label: "зар_внять", correct: "заровнять", options: ["заровнять", "заравнять"]),
    Word(rule: 1, label: "зар_сли", correct: "заросли", options: ["заросли", "зарасли"]),
    Word(rule: 1, label: "заст_лать", correct: "застилать", options: ["застилать", "застелать"]),
    Word(rule: 11, label: "затв_рить", correct: "затворить", options: ["затворить", "затварить"]),
    Word(rule: 1, label: "изб_рать", correct: "избирать", options: ["избирать", "изберать"]),
    Word(rule: 1, label: "изб_ру", correct: "изберу", options: ["изберу", "избиру"]),
    Word(rule: 6, label: "изл_гать", correct: "излагать", options: ["излагать", "излогать"]),
    Word(rule: 6, label: "изл_жение", correct: "изложение", options: ["изложение", "излажение"]),
    Word(rule: 4, label: "к_сательная", correct: "касательная", options: ["касательная", "косательная"]),
    Word(rule: 4, label: "к_саться", correct: "касаться", options: ["касаться", "косаться"]),
    Word(rule: 4, label: "к_снуться", correct: "коснуться", options: ["коснуться", "каснуться"]),
    Word(rule: 7, label: "м_кать", correct: "макать", options: ["макать", "мокать"]),
    Word(rule: 1, label: "наб_рать", correct: "набирать", options: ["набирать", "наберать"]),
    Word(rule: 1, label: "наб_ру", correct: "наберу", options: ["наберу", "набиру"]),
    Word(rule: 5, label: "накл_ниться", correct: "наклониться", options: ["наклониться", "накланиться"]),
    Word(rule: 1, label: "нан_мать", correct: "нанимать", options: ["нанимать", "нанемать"]),
    Word(rule: 12, label: "нар_стить", correct: "нарастить", options: ["нарастить", "наростить"]),
    Word(rule: 1, label: "нач_нать", correct: "начинать", options: ["начинать", "наченать"]),
    Word(rule: 7, label: "непром_каемый", correct: "непромокаемый", options: ["непромокаемый", "непромакаемый"]),
    Word(rule: 9, label: "неср_вненный", correct: "несравненный", options: ["несравненный", "несровненный"]),
    Word(rule: 6, label: "обл_гать", correct: "облагать", options: ["облагать", "облогать"]),
    Word(rule: 6, label: "обл_жение", correct: "обложение", options: ["обложение", "облажение"]),
    Word(rule: 7, label: "обм_кнуть", correct: "обмакнуть", options: ["обмакнуть", "обмокнуть"]),
    Word(rule: 1, label: "обм_нать", correct: "обминать", options: ["обминать", "обменать"]),
    Word(rule: 1, label: "обт_рать", correct: "обтирать", options: ["обтирать", "обтерать"]),
    Word(rule: 1, label: "обт_реть", correct: "обтереть", options: ["обтереть", "обтиреть"]),
    Word(rule: 3, label: "оз_рённый", correct: "озарённый", options: ["озарённый", "озорённый"]),
    Word(rule: 3, label: "оз_рять", correct: "озарять", options: ["озарять", "озорять"]),
    Word(rule: 1, label: "отд_рать", correct: "отдирать", options: ["отдирать", "отдерать"]),
    Word(rule: 1, label: "отд_решь", correct: "отдерешь", options: ["отдерешь", "отдирешь"]),
    Word(rule: 1, label: "отж_мать", correct: "отжимать", options: ["отжимать", "отжемать"]),
    Word(rule: 6, label: "отл_жить", correct: "отложить", options: ["отложить", "отлажить"]),
    Word(rule: 1, label: "отм_рать", correct: "отмирать", options: ["отмирать", "отмерать"]),
    Word(rule: 1, label: "отмереть", correct: "отмереть", options: ["отмереть", "отмиреть"]),
    Word(rule: 1, label: "отп_рать", correct: "отпирать", options: ["отпирать", "отперать"]),
    Word(rule: 1, label: "отп_реть", correct: "отпереть", options: ["отпереть", "отпиреть"]),
    Word(rule: 12, label: "отр_стить", correct: "отрастить", options: ["отрастить", "отростить"]),
    Word(rule: 1, label: "переж_мать", correct: "пережимать", options: ["пережимать", "пережемать"]),
    Word(rule: 8, label: "пл_вунец", correct: "плавунец", options: ["плавунец", "пловунец"]),
    Word(rule: 8, label: "пл_вучесть", correct: "плавучесть", options: ["плавучесть", "пловучесть"]),
    Word(rule: 8, label: "пл_вучий", correct: "плавучий", options: ["плавучий", "пловучий"]),
    Word(rule: 2, label: "пог_релица", correct: "погорелица", options: ["погорелица", "погарелица"]),
    Word(rule: 1, label: "подп_рать", correct: "подпирать", options: ["подпирать", "подперать"]),
    Word(rule: 1, label: "подп_реть", correct: "подпереть", options: ["подпереть", "подпиреть"]),
    Word(rule: 9, label: "подр_внять", correct: "подровнять", options: ["подровнять", "подравнять"]),
    Word(rule: 10, label: "подск_чить", correct: "подскочить", options: ["подскочить", "подскачить"]),
    Word(rule: 1, label: "подст_лать", correct: "подстилать", options: ["подстилать", "подстелать"]),
    Word(rule: 1, label: "подстелить", correct: "подстелить", options: ["подстелить", "подстилить"]),
    Word(rule: 1, label: "подсч_тать", correct: "подсчитать", options: ["подсчитать", "подсчетать"]),
    Word(rule: 5, label: "покл_нение", correct: "поклонение", options: ["поклонение", "покланение"]),
    Word(rule: 5, label: "покл_ниться", correct: "поклониться", options: ["поклониться", "покланиться"]),
    Word(rule: 8, label: "попл_вок", correct: "поплавок", options: ["поплавок", "попловок"]),
    Word(rule: 9, label: "пор_вняться", correct: "поравняться", options: ["поравняться", "поровняться"]),
    Word(rule: 1, label: "пор_сль", correct: "поросль", options: ["поросль", "порасль"]),
    Word(rule: 6, label: "предл_гать", correct: "предлагать", options: ["предлагать", "предлогать"]),
    Word(rule: 1, label: "предложить", correct: "предложить", options: ["предложить", "предлажить"]),
    Word(rule: 1, label: "приж_гать", correct: "прижигать", options: ["прижигать", "прижегать"]),
    Word(rule: 1, label: "приж_гать", correct: "прижигать", options: ["прижигать", "прижегать"]),
    Word(rule: 4, label: "прик_сновение", correct: "прикосновение", options: ["прикосновение", "прикасновение"]),
    Word(rule: 6, label: "прил_гательное", correct: "прилагательное", options: ["прилагательное", "прилогательное"]),
    Word(rule: 6, label: "прил_жение", correct: "приложение", options: ["приложение", "прилажение"]),
    Word(rule: 1, label: "присл_ниться", correct: "прислониться", options: ["прислониться", "присланиться"]),
    Word(rule: 5, label: "прокл_нать", correct: "проклинать", options: ["проклинать", "прокленать"]),
    Word(rule: 7, label: "пром_кательная", correct: "промокательная", options: ["промокательная", "промакательная"]),
    Word(rule: 10, label: "проск_кал", correct: "проскакал", options: ["проскакал", "проскокал"]),
    Word(rule: 10, label: "проск_чил", correct: "проскочил", options: ["проскочил", "проскачил"]),
    Word(rule: 9, label: "р_вноправие", correct: "равноправие", options: ["равноправие", "ровноправие"]),
    Word(rule: 1, label: "разб_рать", correct: "разбирать", options: ["разбирать", "разберать"]),
    Word(rule: 1, label: "разж_гал", correct: "разжигал", options: ["разжигал", "разжегал"]),
    Word(rule: 1, label: "расст_лать", correct: "расстилать", options: ["расстилать", "расстелать"]),
    Word(rule: 1, label: "расст_лить", correct: "расстелить", options: ["расстелить", "расстилить"]),
    Word(rule: 1, label: "раст_рать", correct: "растирать", options: ["растирать", "растерать"]),
    Word(rule: 1, label: "раст_реть", correct: "растереть", options: ["растереть", "растиреть"]),
    Word(rule: 1, label: "сж_гать", correct: "сжигать", options: ["сжигать", "сжегать"]),
    Word(rule: 10, label: "ск_калка", correct: "скакалка", options: ["скакалка", "скокалка"]),
    Word(rule: 10, label: "ск_кать", correct: "скакать", options: ["скакать", "скокать"]),
    Word(rule: 5, label: "скл_нение", correct: "склонение", options: ["склонение", "скланение"]),
    Word(rule: 1, label: "сосч_тать", correct: "сосчитать", options: ["сосчитать", "сосчетать"]),
    Word(rule: 11, label: "сотв_рить", correct: "сотворить", options: ["сотворить", "сотварить"]),
    Word(rule: 8, label: "спл_влять", correct: "сплавлять", options: ["сплавлять", "спловлять"]),
    Word(rule: 9, label: "ср_внять", correct: "сравнять", options: ["сравнять", "сровнять"]),
    Word(rule: 1, label: "ст_лить", correct: "стелить", options: ["стелить", "стилить"]),
    Word(rule: 1, label: "ст_рать", correct: "стирать", options: ["стирать", "стерать"]),
    Word(rule: 1, label: "ст_реть", correct: "стереть", options: ["стереть", "стиреть"]),
    Word(rule: 11, label: "тв_рец", correct: "творец", options: ["творец", "тварец"]),
    Word(rule: 11, label: "тв_рить", correct: "творить", options: ["творить", "тварить"]),
    Word(rule: 1, label: "уб_рать", correct: "убирать", options: ["убирать", "уберать"]),
    Word(rule: 1, label: "уб_ру", correct: "уберу", options: ["уберу", "убиру"]),
    Word(rule: 2, label: "уг_реть", correct: "угореть", options: ["угореть", "угареть"]),
    Word(rule: 1, label: "уд_рать", correct: "удирать", options: ["удирать", "удерать"]),
    Word(rule: 1, label: "уд_ру", correct: "удеру", options: ["удеру", "удиру"]),
    Word(rule: 1, label: "ум_рать", correct: "умирать", options: ["умирать", "умерать"]),
    Word(rule: 1, label: "ум_реть", correct: "умереть", options: ["умереть", "умиреть"]),
    Word(rule: 1, label: "уп_раться", correct: "упираться", options: ["упираться", "уператься"]),
    Word(rule: 1, label: "уп_реться", correct: "упереться", options: ["упереться", "упиреться"]),
    Word(rule: 1, label: "упом_нание", correct: "упоминание", options: ["упоминание", "упоменание"]),
    Word(rule: 9, label: "ур_внение", correct: "уравнение", options: ["уравнение", "уровнение"]),
    Word(rule: 11, label: "утв_рь", correct: "утварь", options: ["утварь", "утворь"]),
    Word(rule: 2, label: "выг_рки", correct: "выгарки", options: ["выгарки", "выгорки"]),
    Word(rule: 12, label: "выр_сток", correct: "выросток", options: ["выросток", "вырасток"]),
    Word(rule: 3, label: "з_ревать", correct: "зоревать", options: ["зоревать", "заревать"]),
    Word(rule: 3, label: "з_ревой", correct: "зоревой", options: ["зоревой", "заревой"]),
    Word(rule: 2, label: "изг_рь", correct: "изгарь", options: ["изгарь", "изгорь"]),
    Word(rule: 12, label: "на выр_ст", correct: "на вырост", options: ["на вырост", "на выраст"]),
    Word(rule: 1, label: "отр_сль", correct: "отрасль", options: ["отрасль", "отросль"]),
    Word(rule: 8, label: "пл_вец", correct: "пловец", options: ["пловец", "плавец"]),
    Word(rule: 8, label: "пл_вун", correct: "плывун", options: ["плывун", "плавун"]),
    Word(rule: 8, label: "пл_вчиха", correct: "пловчиха", options: ["пловчиха", "плавчиха"]),
    Word(rule: 12, label: "подр_стковый", correct: "подростковый", options: ["подростковый", "подрастковый"]),
    Word(rule: 6, label: "пол_г", correct: "полог", options: ["полог", "полаг"]),
    Word(rule: 9, label: "пор_вну", correct: "поровну", options: ["поровну", "поравну"]),
    Word(rule: 2, label: "приг_рь", correct: "пригарь", options: ["пригарь", "пригорь"]),
    Word(rule: 1, label: "р_весник", correct: "ровесник", options: ["ровесник", "равесник"]),
    Word(rule: 9, label: "р_внина", correct: "равнина", options: ["равнина", "ровнина"]),
    Word(rule: 1, label: "Р_стислав", correct: "Ростислав", options: ["Ростислав", "Растислав"]),
    Word(rule: 12, label: "р_стовщик", correct: "ростовщик", options: ["ростовщик", "растовщик"]),
    Word(rule: 12, label: "р_сток", correct: "росток", options: ["росток", "расток"]),
    Word(rule: 1, label: "Ростов-на-Дону", correct: "Р_стов-на-Дону", options: ["Ростов-на-Дону", "Растов-на-Дону"]),
    Word(rule: 10, label: "ск_чите", correct: "скачите", options: ["скачите", "скочите"]),
    Word(rule: 10, label: "ск_чок", correct: "скачок", options: ["скачок", "скочок"]),
    Word(rule: 10, label: "ск_чу", correct: "скачу", options: ["скачу", "скочу"]),
    Word(rule: 1, label: "словосоч_тание", correct: "словосочетание", options: ["словосочетание", "словосочитание"]),
    Word(rule: 1, label: "соч_тание", correct: "сочетание", options: ["сочетание", "сочитание"]),
    Word(rule: 1, label: "соч_тать", correct: "сочетать", options: ["сочетать", "сочитать"]),
    Word(rule: 1, label: "ур_вень", correct: "уровень", options: ["уровень", "уравень"]),
    Word(rule: 1, label: "ч_та", correct: "чета", options: ["чета", "чита"])
];

let Rules = [
    "Something went wrong",
    "№1. В корнях -жа-, -жим-; -ча-,-чин-; -ня-,-ним-; -мя-, -мин-; -кля-, -клин-; -кас-,-кос-; -бер-, -бир-; -тер-, -тир-; -мер-, -мир-; -стил-,-стел-; -блист-, -блест-; -пер-,-пир-; -дер-, -дир-; -жег-, -жиг-; -чет-, -чит-., если после корня идет суффикс -А-, то в корне пишем И, если нет суффикса -А-, то в корне пишем -Е-.",
    "№2. В корнях -гар-;-гор- под ударением пишется А, без ударения – О. Исключения: выгарки, изгарь, пригарь.",
    "№3. В корнях -зар-;-зор- под ударением – О, без ударения – А. Исключения: зоревать, зоревой, зарево, зорянка (зарянка).",
    "№4. В корнях -кас-;-кос- в корне пишется А ,если после корня суффикс -А-, во всех остальных случаях пишется О.",
    "№5. В  корнях -клан-;-клон- без ударения пишется -О-, под ударением – как слышится.",
    "№6. В корнях -лаг-;-лож- -А- в корне пишется перед Г, -О- перед Ж.",
    "№7. В корнях -мак-;-мок- –А- пишется в корне со значением погружения в жидкость, О – пропускать, впитывать жидкость.",
    "№8. В корнях -плав-;-плов- во всех случаях пишется А, кроме исключений: пловец, пловчиха, пловцы.",
    "№9. В корнях -равн-;-ровн- буква А пишется в корне со значением равный, одинаковый, сравнение, О – со значением ровный, гладкий, прямой. Исключение: равнина.",
    "№10. В корнях -скак-;-скоч- буква А в корне пишется перед К, буква О перед Ч; исключение: скачок, личные формы глагола скакать, скачу и тд.",
    "№11. В корнях -твар-;-твор- О пишется в корне – без ударения, под ударением – как слышится; исключение: утварь.",
    "№12. В корнях -раст-;-ращ-;-рос- буква А пишется в корне перед СТ, Щ; О пишется перед С; исключения: отрасль, росток, Ростов, Ростислав, ростовщик, подросток,выросток на вырост."
];

let debug = true;
let wordCount = 10;
